### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by Nziie3** [AltF02/HasteBinWrapper#1]
After installing how you said (with git), there is a `ModuleNotFoundError` when using the examples you provided.

`ModuleNotFoundError: No module named 'HasteBin'`

what I did:

```py
import HasteBin
haste = HasteBin.Session(links=True)
link = await haste.upload('test')
return link
```
<kbd>⚠ FIX:  change 'HasteBin' to 'hastebin' for importing

**Comment by AltF02** [comment]
Fixed in #2
